@ECHO off 
ECHO *
ECHO * UPDATE SELENIUM HUB AND NODES:
ECHO *
SET SOURCE_PATH=C:\Data\Dev\SeleniumGrid\
SET SOURCE_HUB=startSeleniumHub.bat
SET SOURCE_HUB_CFG=hubconfig.json
SET SOURCE_NODE=startSeleniumNode.bat
SET SOURCE_NODE_CFG=nodeconfig.json

SET DEST_1=Z:\Automation\SeleniumGrid\
SET DEST_2=Y:\Automation\SeleniumGrid\
SET DEST_3=X:\Automation\SeleniumGrid\
SET DEST_4=X:\Automation\SeleniumGrid\

ECHO *
ECHO * COPY HUB AND NODE:
ECHO *
REM XCOPY /Y /F /R %SOURCE_PATH%%SOURCE_HUB% 		%DEST_1%
XCOPY /Y /F /R %SOURCE_PATH%%SOURCE_HUB_CFG% 	%DEST_1%
REM XCOPY /Y /F /R %SOURCE_PATH%%SOURCE_NODE% 		%DEST_1%
XCOPY /Y /F /R %SOURCE_PATH%%SOURCE_NODE_CFG% 	%DEST_1%

ECHO *
ECHO * COPY NODES:
ECHO *
REM XCOPY /Y /F /R %SOURCE_PATH%%SOURCE_NODE% 		%DEST_2%
XCOPY /Y /F /R %SOURCE_PATH%%SOURCE_NODE_CFG% 	%DEST_2%

REM XCOPY /Y /F /R %SOURCE_PATH%%SOURCE_NODE% 		%DEST_3%
XCOPY /Y /F /R %SOURCE_PATH%%SOURCE_NODE_CFG% 	%DEST_3%

REM XCOPY /Y /F /R %SOURCE_PATH%%SOURCE_NODE% 		%DEST_4%
REM XCOPY /Y /F /R %SOURCE_PATH%%SOURCE_NODE_CFG% 	%DEST_4%

ECHO *
PAUSE