@ECHO off

SET BUILD_ARTIFACTS_PATH=%1
SET TEXTURA_PRODUCT=%2
SET AUTOMATION_SERVER=%COMPUTERNAME%
SET WINDOWS_PATH=%windir%
SET WINDOWS_SYSTEM32=%WINDOWS_PATH%\system32
SET ARTIFACTS_EXCLUSIONS=C:\Automation\Textura\Framework\src\main\scripts\jenkins

SET JENKINS_JOB_NAME=%JOB_NAME%
SET JENKINS_BUILD_ID=%BUILD_ID%
SET JENKINS_BUILD_URL=%BUILD_URL%
SET JENKINS_BUILD_TAG=%BUILD_TAG%
SET JENKINS_BUILD_NUMBER=%BUILD_NUMBER%
SET JENKINS_WORKSPACE=%WORKSPACE%
SET JENKINS_HOME=%JENKINS_HOME%
SET JENKINS_BUILD=%JENKINS_JOB_NAME%_%JENKINS_BUILD_NUMBER%
SET JENKINS_BUILD_LOG=%BUILD_ARTIFACTS_PATH%\%JENKINS_BUILD%\%JENKINS_BUILD%_INFO.log

ECHO Saving build artifacts in: %BUILD_ARTIFACTS_PATH%\%JENKINS_BUILD%
MKDIR %BUILD_ARTIFACTS_PATH%\%JENKINS_BUILD%

ECHO Copying build artifacts...
"%WINDOWS_SYSTEM32%\xcopy.exe" /S /R /Y /Q /EXCLUDE:%ARTIFACTS_EXCLUSIONS%\archive_build_artifacts_excl.txt "%JENKINS_WORKSPACE%\%TEXTURA_PRODUCT%\target" "%BUILD_ARTIFACTS_PATH%\%JENKINS_BUILD%\"
"%WINDOWS_SYSTEM32%\xcopy.exe" /S /R /Y /Q "%JENKINS_WORKSPACE%\%TEXTURA_PRODUCT%\testconfig.xml" "%BUILD_ARTIFACTS_PATH%\%JENKINS_BUILD%\"
"%WINDOWS_SYSTEM32%\xcopy.exe" /S /R /Y /Q "%JENKINS_WORKSPACE%\%TEXTURA_PRODUCT%\tng*" "%BUILD_ARTIFACTS_PATH%\%JENKINS_BUILD%\"
"%WINDOWS_SYSTEM32%\xcopy.exe" /S /R /Y /Q "%JENKINS_WORKSPACE%\%TEXTURA_PRODUCT%\environment.xml" "%BUILD_ARTIFACTS_PATH%\%JENKINS_BUILD%\"

ECHO Saving build artifacts info in: %JENKINS_BUILD_LOG%
ECHO *                                              >  %JENKINS_BUILD_LOG%
ECHO * Automation build on %COMPUTERNAME%           >> %JENKINS_BUILD_LOG%
ECHO *                                              >> %JENKINS_BUILD_LOG%
ECHO Jenkins Build URL   : %JENKINS_BUILD_URL%      >> %JENKINS_BUILD_LOG%
ECHO Jenkins Build Start : %JENKINS_BUILD_ID%       >> %JENKINS_BUILD_LOG%
ECHO Jenkins Build Num   : %JENKINS_BUILD_NUMBER%   >> %JENKINS_BUILD_LOG%
ECHO Jenkins Job Name    : %JENKINS_JOB_NAME%       >> %JENKINS_BUILD_LOG%
ECHO Jenkins Build Tag   : %JENKINS_BUILD_TAG%      >> %JENKINS_BUILD_LOG%
ECHO Jenkins Home        : %JENKINS_HOME%           >> %JENKINS_BUILD_LOG%
ECHO Product             : %TEXTURA_PRODUCT%        >> %JENKINS_BUILD_LOG%
ECHO Build Server        : %AUTOMATION_SERVER%      >> %JENKINS_BUILD_LOG%
ECHO Build Workspace     : %JENKINS_WORKSPACE%      >> %JENKINS_BUILD_LOG%
ECHO Build Artifacts     : %BUILD_ARTIFACTS_PATH%   >> %JENKINS_BUILD_LOG%