@ECHO off
SET HOSTNAME=%COMPUTERNAME%
SET JENKINS_SERVER_TEXTURA=DFJENKINSQA1
SET JENKINS_SERVER_ENVAAS=ESTPMJENKINS1
SET TEXTURA_DOMAIN=.TEXTURALLC.NET
SET ORACLE_DOMAIN=.US.ORACLE.COM

SET JENKINS_SERVER=%JENKINS_SERVER_TEXTURA%
SET DOMAIN=%TEXTURA_DOMAIN%

IF NOT X%HOSTNAME:ESTPM=%==X%HOSTNAME% (
SET JENKINS_SERVER=%JENKINS_SERVER_ENVAAS%
SET DOMAIN=%ORACLE_DOMAIN%
)

IF NOT X%HOSTNAME:DFAUTOWS=%==X%HOSTNAME% (
SET JENKINS_SERVER=%JENKINS_SERVER_ENVAAS%
SET DOMAIN=%ORACLE_DOMAIN%
)

TITLE Jenkins Client: %COMPUTERNAME%, Server: %JENKINS_SERVER%

ECHO *
ECHO *
ECHO * Start Jenkins client on host: %HOSTNAME%
ECHO * Connected to Jenkins Server:  %JENKINS_SERVER%%DOMAIN%
ECHO *
ECHO *

REM Wait for VM's network card to initialize
TIMEOUT /T 5 /NOBREAK

java -jar C:\Automation\repository\resources\jenkins\agent.jar -jnlpUrl http://%JENKINS_SERVER%%DOMAIN%:8080/computer/%HOSTNAME%/slave-agent.jnlp

PAUSE
