taskkill.exe /F /IM firefox*
taskkill.exe /F /IM WerFault.exe*
taskkill.exe /F /IM plugin-container.exe*
taskkill.exe /F /IM iexplore*
taskkill.exe /F /IM chrome.exe*
taskkill.exe /F /IM chromedriver.exe*
taskkill.exe /F /IM AcroRd32.exe*
taskkill.exe /F /IM PsExec.exe*
taskkill.exe /F /IM CloseBreakpointFirefoxWindow.exe*